/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_pocketmagic_android_mycursoroverlay_SensorService */

#ifndef _Included_net_pocketmagic_android_mycursoroverlay_SensorService
#define _Included_net_pocketmagic_android_mycursoroverlay_SensorService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_pocketmagic_android_mycursoroverlay_SensorService
 * Method:    touch_check
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_pocketmagic_android_mycursoroverlay_SensorService_touch_1check
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
