/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lge_updownupupdown_BootSvc */

#ifndef _Included_com_lge_updownupupdown_BootSvc
#define _Included_com_lge_updownupupdown_BootSvc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lge_updownupupdown_BootSvc
 * Method:    pattern_check
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_lge_updownupupdown_BootSvc_pattern_1check
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_lge_updownupupdown_BootSvc_receiver */

#ifndef _Included_com_lge_updownupupdown_BootSvc_receiver
#define _Included_com_lge_updownupupdown_BootSvc_receiver
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
