/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_pocketmagic_android_mycursoroverlay_Input */

#ifndef _Included_net_pocketmagic_android_mycursoroverlay_Input
#define _Included_net_pocketmagic_android_mycursoroverlay_Input
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_pocketmagic_android_mycursoroverlay_Input
 * Method:    hanaInput
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_pocketmagic_android_mycursoroverlay_Input_hanaInput
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
